services:
  postgres:
    image: 'postgres:16.3'
    environment:
      - 'POSTGRES_DB=seniorhotel'
      - 'POSTGRES_PASSWORD=hotel'
      - 'POSTGRES_USER=hotel_user'
    ports:
      - '5432:5432'
